version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: homepage-postgres-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
  homepage:
    image: homepage
    container_name: homepage
    build:
      context: .
      dockerfile: dockerfile
    command: flask run --host=0.0.0.0 --debug
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  postgres-db:
